name: Production Build

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    env:
      APP_VERSION: 8.0.1
      CLOUD_SPACE: production
      SERVER_BASE_PATH: /csb

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6

      - name: Install server app dependencies
        run: npm ci
        working-directory: app/server

      - name: Install client app dependencies
        run: npm ci --registry=https://registry.npmjs.org --replace-registry-host=always
        working-directory: app/client

      - name: Build client app and move files to server app
        run: |
          VITE_SERVER_BASE_PATH="$SERVER_BASE_PATH" \
            VITE_CLOUD_SPACE="$CLOUD_SPACE" \
            npm run build
          rm ../server/app/public/index.html
          cd build
          mv * ../../server/app/public
        working-directory: app/client

      - name: Remove unnecessary server app files
        run: rm -rf .env.example .eslintrc.js .prettierrc.json
        working-directory: app/server

      - name: Remove NCES JSON files, as they're served from S3 in production
        run: rm -rf nces-2023.json nces-2024.json
        working-directory: app/server/app/content

      - name: Copy production manifest file to server app
        run: cp manifest-production.yml server/manifest-production.yml
        working-directory: app

      - name: Create production artifact
        uses: actions/upload-artifact@v4
        with:
          name: csb-v${{ env.APP_VERSION }}
          path: app/server
